#- name: Generate random ID
#  ansible.builtin.shell: sleep 1 ; date | md5sum | awk '{print $1}'
#  register: random
#
#- name: Create Job Template
#  ansible.builtin.template:
#    src: m-pipeline.xml
#    dest: /tmp/m-pipeline.xml
#  vars:
#    random_id: "{{random.stdout}}"
#
#- name: Create a jenkins job using basic authentication
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/m-pipeline.xml') }}"
#    name: "CI-Pipelines/{{item}}"
#    password: admin1234
#    url: http://172.31.14.209:8080
#    user: admin